### ISSUE TITLE
use strict 模式下的问题

### ISSUE THREAD

**Issue by huxinghai** [pipi32167/pomelo-http-plugin#3]
环境：
node   v0.12.0 
npm    2.5.1

lib/components/http.js
你使用了use strict模式

Http.name = '**Http**';

这样赋值会报错

TypeError: Cannot assign to read only property 'name'

但是在我本地不会，可能跟node也有关系吧！

**Comment by pipi32167** [comment]
貌似node v0.12.0增加了Function的只读属性name，这个属性是ECMAScript 6标准新增的。

尝试用node v0.12.0运行了下pomelo项目，发现问题还是蛮多的，建议暂缓使用node v0.12.0。
