### ISSUE TITLE
升级express到3.x 4.x版本

### ISSUE THREAD

**Issue by weitufei** [pipi32167/pomelo-http-plugin#5]
用新node版本运行的时候报警告
[WARN] console - connect.multipart() will be removed in connect 3.0
查了一下说是express 2.x 和3.x的api不一样，
提议实现各 express 3.x的版本版本

**Comment by pipi32167** [comment]
这只是提供一个http api服务的插件而已，并不影响使用。也没有必要升级到4.x版本。
