### ISSUE TITLE
公网ip访问gamehttp提示aborted

### ISSUE THREAD

**Issue by weitufei** [pipi32167/pomelo-http-plugin#6]
按照文档做了个demo，运行之后可以用http://127.0.0.1:3001 访问成功，改用电脑在局域网的ip访问http:192.168.1.11:11:3001 访问失败，提示aborted；

1.我试着把防火墙也关了，也不行；
2.我又用express做了个demo，两种地址都能访问成功。
3.把http.json里的host改成192.168.1.11:11，也访问失败

请问是要在pome-http-plugin的什么地方加上什么其他设置才能成功么，或者其他的什么办法

**Comment by pipi32167** [comment]
192.168.1.11:11

这个不是合法ip吧

**Comment by weitufei** [comment]
哦不好意思，192.168.1.11:3001写错了，，总结出来我现在遇到的情况就是 挂到服务器就不行了。

**Comment by pipi32167** [comment]
不确定，你将你的代码和配置贴上来看看，操作系统环境、node版本是什么？

**Comment by txiejun** [comment]
这个问题有解决么?

**Comment by pipi32167** [comment]
@txiejun 你也遇到同样的问题吗？将你的代码和配置贴上来看看，操作系统环境、node版本是什么？
