### ISSUE TITLE
缺少了raw body的数据解析

### ISSUE THREAD

**Issue by louisome** [pipi32167/pomelo-http-plugin#7]
如果需要加上raw body的数据解析，大概就是源码上加上：
`
this.http.use(function(req, res, next) {
        if(!req.is('text/plain'))
            return next();

        req.rawBody = '';

        req.setEncoding('utf8');

        req.on('data', function (chunk) {
            req.rawBody += chunk;
        });

        req.on('end', function() {
            next();
        });

    });
`

**Comment by pipi32167** [comment]
什么情况下有传raw body的需求？正常情况下传query或者body就可以了吧？

**Comment by louisome** [comment]
主要是我自己现在测试的时候都会遇到，所以就留个言给有需要的人嘛，比如我现在用postman去测试API，传个raw的json数据过去的时候，发现body都是为空的。。后来才发现没有这个的数据读取，所以就反馈一下咯，见需吧~
